### ISSUE TITLE
Add option to ignore files

### ISSUE THREAD

**Issue by santisoler** [fatiando/burocrata#7]
**Description of the desired feature:**

Would be nice if we can include a list of files in the `pyproject.toml` that we don't want to be checked or modified by burocrata. The syntax could be similar to what `isort` does with [`skip`](https://pycqa.github.io/isort/docs/configuration/options.html#skip), `flake8` with [`exclude`](https://flake8.pycqa.org/en/latest/user/configuration.html), and `ruff` with [`exclude`](https://docs.astral.sh/ruff/configuration/).

It would be nice if we can list files and/or globs. For example:

```toml
[tool.burocrata]
notice = '''
# Copyright (c) YYYY Name of Developer.
# Distributed under the terms of the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause'''
exclude = ["foo/bar.py", "lorem/*.py"]
```

This idea originated in https://github.com/orgs/fatiando/discussions/139#discussioncomment-8647144

**Are you willing to help implement and maintain this feature?** 

That will be fun!
